# ==============================================
# AlertManager Configuration
# Internal SMTP Setup
# ==============================================

global:
  # SMTP Configuration
  smtp_smarthost: 'postfix:587'
  smtp_from: 'noreply@monitoring.local'
  smtp_auth_username: 'monitoring@monitoring.local'
  smtp_auth_password: 'your-smtp-password'
  smtp_require_tls: false
  smtp_hello: 'monitoring.local'

# Route tree for alert distribution
route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
    
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 5m
      repeat_interval: 2h
    
    # Info alerts
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 10m
      repeat_interval: 24h

# Inhibition rules - suppress redundant alerts
inhibit_rules:
  # Suppress warning if critical is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
  
  # Suppress info if warning is firing
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'instance']

# Notification receivers
receivers:
  # Default receiver
  - name: 'default-receiver'
    email_configs:
      - to: 'chennybirru@gmail.com'
        from: 'noreply@monitoring.local'
        html: |
          <h2>Alert Fired</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Instance:</strong> {{ .GroupLabels.instance }}</p>
          {{ range .Alerts }}
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          {{ end }}

  # Critical alerts
  - name: 'critical-alerts'
    email_configs:
      - to: 'chennybirru@gmail.com'
        from: 'noreply@monitoring.local'
        html: |
          <h2>Critical Alert Fired</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Instance:</strong> {{ .GroupLabels.instance }}</p>
          <p><strong>Severity:</strong> Critical</p>
          {{ range .Alerts }}
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          {{ end }}

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'chennybirru@gmail.com'
        from: 'noreply@monitoring.local'
        html: |
          <h2>Warning Alert Fired</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Instance:</strong> {{ .GroupLabels.instance }}</p>
          <p><strong>Severity:</strong> Warning</p>
          {{ range .Alerts }}
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          {{ end }}

  # Info alerts
  - name: 'info-alerts'
    email_configs:
      - to: 'chennybirru@gmail.com'
        from: 'noreply@monitoring.local'
        html: |
          <h2>Info Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Instance:</strong> {{ .GroupLabels.instance }}</p>
          <p><strong>Severity:</strong> Info</p>
          {{ range .Alerts }}
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          {{ end }}
