# ==============================================
# Facebook/Meta AlertManager Configuration
# Enterprise-Grade Alerting Setup
# ==============================================

global:
  # Development SMTP (MailHog)
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'noreply-monitoring@facebook.com'
  smtp_require_tls: false
  
  # Production SMTP (Postfix) - uncomment for production
  # smtp_smarthost: 'postfix:587'
  # smtp_from: 'noreply-monitoring@facebook.com'
  # smtp_auth_username: 'monitoring@facebook.com'
  # smtp_auth_password: '${SMTP_PASSWORD}'
  # smtp_require_tls: true
  
  # Slack global config
  slack_api_url: '${SLACK_API_URL}'
  
  # PagerDuty global config
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
  
  # HTTP global config
  http_config:
    proxy_url: 'http://proxy.facebook.com:8080'

# Templates for custom notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert distribution
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts - immediate PagerDuty + Slack
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
      routes:
        # Database alerts
        - match:
            service: postgres
          receiver: 'database-team'
        # Infrastructure alerts  
        - match:
            service: kubernetes
          receiver: 'platform-team'
    
    # Warning alerts - Slack only
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 5m
      repeat_interval: 2h
    
    # Info alerts - email only
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 10m
      repeat_interval: 24h
    
    # Development environment alerts
    - match:
        environment: development
      receiver: 'dev-alerts'
      repeat_interval: 24h
    
    # Staging environment alerts
    - match:
        environment: staging
      receiver: 'staging-alerts'
      repeat_interval: 6h

# Inhibition rules - suppress redundant alerts
inhibit_rules:
  # Suppress warning if critical is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  
  # Suppress info if warning is firing
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'cluster', 'service']
  
  # Suppress node alerts if cluster is down
  - source_match:
      alertname: 'ClusterDown'
    target_match_re:
      alertname: 'Node.*'
    equal: ['cluster']

# Notification receivers
receivers:
  # Default receiver
  - name: 'default-receiver'
    slack_configs:
      - channel: '#platform-reliability'
        username: 'FB-Monitoring'
        icon_emoji: ':warning:'
        title: 'Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true

  # Critical alerts - PagerDuty + Slack + Email
  - name: 'critical-alerts'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_INTEGRATION_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .GroupLabels.instance }}'
        severity: 'critical'
        details:
          firing: '{{ .Alerts.Firing | len }}'
          resolved: '{{ .Alerts.Resolved | len }}'
          alertname: '{{ .GroupLabels.alertname }}'
          instance: '{{ .GroupLabels.instance }}'
    
    slack_configs:
      - channel: '#critical-alerts'
        username: 'FB-Critical-Alerts'
        icon_emoji: ':fire:'
        title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          *Environment:* {{ .GroupLabels.environment }}
          *Service:* {{ .GroupLabels.service }}
          *Instance:* {{ .GroupLabels.instance }}
          
          {{ range .Alerts }}
          *Description:* {{ .Annotations.description }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        color: 'danger'
        send_resolved: true
        actions:
          - type: button
            text: 'Runbook'
            url: '{{ .Annotations.runbook_url }}'
          - type: button
            text: 'Grafana Dashboard'
            url: 'https://grafana.facebook.com/d/{{ .Annotations.dashboard_id }}'
    
    email_configs:
      - to: 'oncall-sre@facebook.com'
        from: 'noreply-monitoring@facebook.com'
        subject: 'CRITICAL ALERT: {{ .GroupLabels.alertname }}'
        html: |
          <h2>Critical Alert Fired</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Environment:</strong> {{ .GroupLabels.environment }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Instance:</strong> {{ .GroupLabels.instance }}</p>
          {{ range .Alerts }}
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Runbook:</strong> <a href="{{ .Annotations.runbook_url }}">Click here</a></p>
          {{ end }}

  # Warning alerts - Slack + Email
  - name: 'warning-alerts'
    slack_configs:
      - channel: '#platform-reliability'
        username: 'FB-Monitoring'
        icon_emoji: ':warning:'
        title: 'WARNING: {{ .GroupLabels.alertname }}'
        text: |
          *Environment:* {{ .GroupLabels.environment }}
          *Service:* {{ .GroupLabels.service }}
          *Instance:* {{ .GroupLabels.instance }}
          
          {{ range .Alerts }}
          {{ .Annotations.description }}
          {{ end }}
        color: 'warning'
        send_resolved: true
    
    email_configs:
      - to: 'platform-team@facebook.com'
        from: 'noreply-monitoring@facebook.com'
        subject: 'WARNING: {{ .GroupLabels.alertname }}'

  # Info alerts - Email only
  - name: 'info-alerts'
    email_configs:
      - to: 'monitoring-info@facebook.com'
        from: 'noreply-monitoring@facebook.com'
        subject: 'INFO: {{ .GroupLabels.alertname }}'

  # Database team alerts
  - name: 'database-team'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_DATABASE_KEY}'
        description: 'Database Alert: {{ .GroupLabels.alertname }}'
        severity: 'critical'
    
    slack_configs:
      - channel: '#database-team'
        username: 'DB-Monitoring'
        icon_emoji: ':database:'
        title: 'Database Alert: {{ .GroupLabels.alertname }}'
        color: 'danger'
        send_resolved: true
    
    email_configs:
      - to: 'database-oncall@facebook.com'
        from: 'noreply-monitoring@facebook.com'
        subject: 'Database Alert: {{ .GroupLabels.alertname }}'

  # Platform team alerts
  - name: 'platform-team'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_PLATFORM_KEY}'
        description: 'Platform Alert: {{ .GroupLabels.alertname }}'
        severity: 'critical'
    
    slack_configs:
      - channel: '#platform-team'
        username: 'Platform-Monitoring'
        icon_emoji: ':gear:'
        title: 'Platform Alert: {{ .GroupLabels.alertname }}'
        color: 'danger'
        send_resolved: true

  # Development alerts
  - name: 'dev-alerts'
    slack_configs:
      - channel: '#dev-alerts'
        username: 'Dev-Monitoring'
        icon_emoji: ':construction:'
        title: 'Dev Alert: {{ .GroupLabels.alertname }}'
        color: 'good'
        send_resolved: true

  # Staging alerts
  - name: 'staging-alerts'
    slack_configs:
      - channel: '#staging-alerts'
        username: 'Staging-Monitoring'
        icon_emoji: ':test_tube:'
        title: 'Staging Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'
        send_resolved: true

  # Microsoft Teams integration (alternative to Slack)
  - name: 'teams-alerts'
    webhook_configs:
      - url: '${TEAMS_WEBHOOK_URL}'
        send_resolved: true
        title: 'Facebook Monitoring Alert'
        text: |
          **Alert:** {{ .GroupLabels.alertname }}
          **Environment:** {{ .GroupLabels.environment }}
          **Severity:** {{ .GroupLabels.severity }}
          {{ range .Alerts }}
          **Description:** {{ .Annotations.description }}
          {{ end }}
